"""Cycle 3 — generates docs/MODEL_CARD.md from the persisted training and
leakage-smell-test artifacts. Run after both src.models.train and
src.models.leakage_check, since the card reports on both.
"""
from __future__ import annotations

import json
from pathlib import Path

from src.config import ARTIFACTS_DIR, MODELS_DIR

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"

LOW_CONFIDENCE_NOTE = " (low confidence -- insufficient sample size for a stable estimate)"


def _per_class_table(per_class: dict) -> str:
    header = "| Class | Precision | Recall | F1 | FPR | PR-AUC | ROC-AUC | Support |\n"
    header += "|---|---|---|---|---|---|---|---|\n"
    rows = []
    for name, m in per_class.items():
        suffix = LOW_CONFIDENCE_NOTE if m["low_confidence"] else ""
        roc = f"{m['roc_auc']:.3f}" if m["roc_auc"] is not None else "n/a"
        rows.append(
            f"| {name}{suffix} | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} | "
            f"{m['fpr']:.4f} | {m['pr_auc']:.3f} | {roc} | {m['support']} |"
        )
    return header + "\n".join(rows)


def _confusion_matrix_table(cm: list, labels: list) -> str:
    header = "| true \\ pred | " + " | ".join(labels) + " |\n"
    header += "|---" * (len(labels) + 1) + "|\n"
    rows = []
    for label, row in zip(labels, cm):
        rows.append(f"| **{label}** | " + " | ".join(str(v) for v in row) + " |")
    return header + "\n".join(rows)


def generate_model_card(xgboost_metrics: dict, rf_metrics: dict, leakage_result: dict) -> str:
    xgb_test = xgboost_metrics["test"]
    rf_test = rf_metrics["test"]
    imbalance = xgboost_metrics["imbalance_config"]

    smote_lines = "\n".join(
        f"- `{name}`: oversampled to {target} rows"
        for name, target in imbalance["smote_target_counts"].items()
    )
    excluded_lines = "\n".join(f"- `{name}`" for name in imbalance["smote_excluded_classes"]) or "- (none)"

    smell_flag = "FLAGGED" if leakage_result["flagged"] else "within threshold"

    botnet_precision_gap = xgb_test["per_class"]["Botnet"]["precision"] - rf_test["per_class"]["Botnet"]["precision"]
    fpr_gap = rf_test["aggregate_benign_fpr"] - xgb_test["aggregate_benign_fpr"]

    return f"""# Model Card — Network Threat & Intrusion Detection

Generated by Pillar 7 Cycle 3 (`src/models/train.py`, `src/models/leakage_check.py`).
Commit: `{xgboost_metrics['commit_hash']}`.

## Models

| | Random Forest (baseline) | XGBoost (primary) |
|---|---|---|
| Role | sanity floor | primary model |
| Features | {rf_metrics['feature_count']} | {xgboost_metrics['feature_count']} |
| Class weighting | balanced | balanced (sample_weight, post-SMOTE) |

## Imbalance handling

Class weighting (`class_weight="balanced"` / per-class `sample_weight`) is the primary
imbalance mechanism for both models, computed **after** SMOTE resampling so the
weights reflect the training distribution the model actually sees (see
`src/models/train.py` for why this order matters).

SMOTE applied to (train fold only, after the split):
{smote_lines}

Excluded from SMOTE (fewer than 10 train-fold samples — oversampling can't manufacture
signal that isn't there):
{excluded_lines}

## Metrics — why not just accuracy (Pillar 4.1)

A classifier that always predicts BENIGN can score above 90% accuracy on this dataset's
class ratios while catching zero attacks. Accuracy is reported below for completeness,
but every other metric here matters more; **PR-AUC leads over ROC-AUC** since ROC-AUC
can look deceptively good under heavy imbalance (Pillar 4.2).

### XGBoost — test split

- **Macro-recall (all 9 classes):** {xgb_test['macro_recall_all_classes']:.4f}
- **Macro-recall (7 stable classes, excl. Heartbleed/Infiltration):** {xgb_test['macro_recall_stable_classes']:.4f}
- Macro-F1: {xgb_test['macro_f1']:.4f} | Weighted-F1: {xgb_test['weighted_f1']:.4f}
- Macro PR-AUC: {xgb_test['macro_pr_auc']:.4f} | Macro ROC-AUC: {xgb_test['macro_roc_auc']:.4f}
- Accuracy: {xgb_test['accuracy']:.4f} (see caveat above — not the headline number)
- Aggregate BENIGN false-positive rate: {xgb_test['aggregate_benign_fpr']:.4f}

#### Per-class (XGBoost, test split)

{_per_class_table(xgb_test['per_class'])}

Heartbleed and Infiltration have very few test-fold examples (a handful of rows), so
their individual recall/precision figures are noisy by construction — reported for
transparency, excluded from the regression-gated macro-recall figure.

#### Confusion matrix (XGBoost, test split)

{_confusion_matrix_table(xgb_test['confusion_matrix'], xgb_test['confusion_matrix_labels'])}

### Random Forest baseline — test split

- Macro-recall (7 stable classes): {rf_test['macro_recall_stable_classes']:.4f}
- Macro-F1: {rf_test['macro_f1']:.4f} | Macro PR-AUC: {rf_test['macro_pr_auc']:.4f}
- Accuracy: {rf_test['accuracy']:.4f}
- Aggregate BENIGN false-positive rate: {rf_test['aggregate_benign_fpr']:.4f}

#### Per-class (Random Forest, test split)

{_per_class_table(rf_test['per_class'])}

XGBoost's edge over the RF baseline is concrete, not just aggregate: Botnet precision is
{xgb_test['per_class']['Botnet']['precision']:.3f} (XGBoost) vs. {rf_test['per_class']['Botnet']['precision']:.3f} (RF), a
{botnet_precision_gap:+.3f} gap, and aggregate BENIGN FPR is {xgb_test['aggregate_benign_fpr']:.4f} (XGBoost) vs.
{rf_test['aggregate_benign_fpr']:.4f} (RF), {fpr_gap:.4f} lower — the empirical basis for XGBoost as the primary model
rather than a general "XGBoost is usually stronger" assumption.

## Day-based leakage smell test (Pillar 2.5)

Every day in this raw CICIDS2017 export is BENIGN plus exactly one attack family, except
Monday, which is 100% BENIGN. That makes a class-complete leave-one-day-out split
well-posed **only** for Monday — holding out any other day erases that day's entire
attack family from training, leaving its recall undefined rather than a meaningful
generalization signal. This smell test therefore holds out Monday, trains a
same-architecture XGBoost on every other day, and compares false-positive rate on
Monday's never-seen benign traffic against the primary model's stratified-test FPR —
the one metric well-defined on an all-BENIGN holdout.

- Stratified-test FPR: {leakage_result['stratified_test_fpr']:.4f}
- Monday-LODO FPR: {leakage_result['lodo_monday_fpr']:.4f}
- Absolute gap: {leakage_result['absolute_gap']:.4f} (threshold: {leakage_result['threshold']}) — **{smell_flag}**

## Known limitations

- **Heartbleed** (11 rows total, 8 in train) is too small for SMOTE or a stable recall
  estimate under any split; not folded into another class, so it remains a documented
  gap rather than a silently inflated number.
- **Novel/unseen attack types:** this is a closed-set classifier — a genuinely new
  attack family will be confidently misclassified as one of the 9 known classes (most
  likely BENIGN or the nearest-behaving family), not flagged as "unknown." Confidence
  thresholding is a forward-looking mitigation, not built in this cycle.
- **Operating threshold:** Pillar 4.3 recommends picking a decision threshold that
  maximizes recall subject to an FPR budget, using the validation-set PR curve, rather
  than a bare 0.5 cutoff — this is a serving-time decision, deferred to Cycle 4 (the
  inference API), not built here.
- Metrics reflect the standard (uncorrected) CICIDS2017 label set (Pillar 2.2); known
  labeling/capture errors documented in `docs/DATASET_CARD.md` are not corrected here.
- The near-perfect separability seen above (ROC-AUC ~1.0, most per-class F1 above 0.98)
  is a documented characteristic of CICIDS2017's traffic-generation methodology (Pillar
  2.2) — synthetic attack tooling against a controlled testbed produces flows that are
  far more statistically distinct than real-world traffic — not evidence this model
  would generalize to production deployment.
"""


def write_model_card(
    artifacts_dir=ARTIFACTS_DIR, models_dir=MODELS_DIR, docs_dir: Path = DOCS_DIR
) -> Path:
    xgboost_dir = models_dir / "xgboost_v1"
    rf_dir = models_dir / "rf_baseline_v1"

    xgboost_metrics = json.loads((xgboost_dir / "metrics.json").read_text())
    rf_metrics = json.loads((rf_dir / "metrics.json").read_text())
    leakage_result = json.loads((xgboost_dir / "leakage_smell_test.json").read_text())

    card = generate_model_card(xgboost_metrics, rf_metrics, leakage_result)
    out_path = docs_dir / "MODEL_CARD.md"
    out_path.write_text(card)
    return out_path


if __name__ == "__main__":
    path = write_model_card()
    print(f"wrote {path}")
